string(ASCII 7   ANSI_BEL)
string(ASCII 8   ANSI_BS)
string(ASCII 9   ANSI_HT)
string(ASCII 10  ANSI_LF)
string(ASCII 11  ANSI_VT)
string(ASCII 12  ANSI_FF)
string(ASCII 13  ANSI_CR)
string(ASCII 27  ANSI_ESC)
string(ASCII 92  ANSI_SLASH)
string(ASCII 127 ANSI_DEL)

set(ANSI_HOME                 "${ANSI_ESC}[H")
set(ANSI_GET_CURSOR_POS       "${ANSI_ESC}[6n")
set(ANSI_SAVE_CURSOR_POS      "${ANSI_ESC}[s")
set(ANSI_RESTORE_CURSOR_POS   "${ANSI_ESC}[u")

set(ANSI_ERASE_END_DISPLAY    "${ANSI_ESC}[0J")
set(ANSI_ERASE_START_DISPLAY  "${ANSI_ESC}[1J")
set(ANSI_ERASE_FULL_DISPLAY   "${ANSI_ESC}[2J")
set(ANSI_ERASE_SAVED_DISPLAY  "${ANSI_ESC}[3J")
set(ANSI_ERASE_END_LINE       "${ANSI_ESC}[0K")
set(ANSI_ERASE_START_LINE     "${ANSI_ESC}[1K")
set(ANSI_ERASE_FULL_LINE      "${ANSI_ESC}[2K")

set(ANSI_RESET_MODE           "${ANSI_ESC}[0m")
set(ANSI_SET_BOLD_MODE        "${ANSI_ESC}[1m")
set(ANSI_UNSET_BOLD_MODE      "${ANSI_ESC}[21m")
set(ANSI_SET_DIM_MODE         "${ANSI_ESC}[2m")
set(ANSI_UNSET_DIM_MODE       "${ANSI_ESC}[22m")
set(ANSI_SET_ITALIC_MODE      "${ANSI_ESC}[3m")
set(ANSI_UNSET_ITALIC_MODE    "${ANSI_ESC}[23m")
set(ANSI_SET_UNDERLINE_MODE   "${ANSI_ESC}[4m")
set(ANSI_UNSET_UNDERLINE_MODE "${ANSI_ESC}[24m")
set(ANSI_SET_BLINKING_MODE    "${ANSI_ESC}[5m")
set(ANSI_UNSET_BLINKING_MODE  "${ANSI_ESC}[25m")
set(ANSI_SET_INVERSE_MODE     "${ANSI_ESC}[7m")
set(ANSI_UNSET_INVERSE_MODE   "${ANSI_ESC}[27m")
set(ANSI_SET_HIDDEN_MODE      "${ANSI_ESC}[8m")
set(ANSI_UNSET_HIDDEN_MODE    "${ANSI_ESC}[28m")
set(ANSI_SET_STRIKEOUT_MODE   "${ANSI_ESC}[9m")
set(ANSI_UNSET_STRIKEOUT_MODE "${ANSI_ESC}[29m")

function(ansi_cursor_up count return_var)
    set(${return_var} "${ANSI_ESC}[${count}A" PARENT_SCOPE)
endfunction()

function(ansi_cursor_down count return_var)
    set(${return_var} "${ANSI_ESC}[${count}B" PARENT_SCOPE)
endfunction()

function(ansi_cursor_right count return_var)
    set(${return_var} "${ANSI_ESC}[${count}C" PARENT_SCOPE)
endfunction()

function(ansi_cursor_left count return_var)
    set(${return_var} "${ANSI_ESC}[${count}D" PARENT_SCOPE)
endfunction()

function(ansi_cursor_next_line count return_var)
    set(${return_var} "${ANSI_ESC}[${count}E" PARENT_SCOPE)
endfunction()

function(ansi_cursor_prev_line count return_var)
    set(${return_var} "${ANSI_ESC}[${count}F" PARENT_SCOPE)
endfunction()

function(ansi_cursor_go_column column return_var)
    set(${return_var} "${ANSI_ESC}[${column}G" PARENT_SCOPE)
endfunction()

function(ansi_fg_rgb r g b return_var)
    set(${return_var} "${ANSI_ESC}[38;2;${r};${g};${b}m" PARENT_SCOPE)
endfunction()

function(ansi_bg_rgb r g b return_var)
    set(${return_var} "${ANSI_ESC}[48;2;${r};${g};${b}m" PARENT_SCOPE)
endfunction()
