include(cmake/utils/fun/cmake_animations.cmake)

set(CMAKE_FURRY_USER 0)

if("${CMAKE_SYSTEM_ID}" STREQUAL "adelie")
    message(STATUS "Adélie Linux? Wait... are you the one with the furry profile picture")
    message(STATUS "and the Compaq Armada E500 from the screenshot page?")
    set(CMAKE_FURRY_USER 1)
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "almalinux")
    message(STATUS "AlmaLinux... the official distro for people with CentOS abandonment issues.")
    message(STATUS "It's okay, Red Hat can't hurt you anymore.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "alpine")
    message(STATUS "Alpine Linux detected. Great choice for a Docker container.")
    message(STATUS "You... you are running this in a container, right? ...Right?")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "altlinux")
    if("${CMAKE_SYSTEM_PROCESSOR}" STREQUAL "e2k")
        message(STATUS "ALT Linux on an Elbrus processor... a true patriot!")
        message(STATUS "I am honored to be compiled with such domestic silicon, comrade.")
    else()
        message(STATUS "ALT Linux... a true classic from the motherland.")
        message(STATUS "I'm surprised you're not compiling this on an Elbrus processor.")
    endif()
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "amzn")
    message(STATUS "Amazon Linux. Hope you enjoy building this for your corporate overlord")
    message(STATUS "on their bespoke, cost-optimized, spyware-as-a-service platform.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "anarchy")
    message(FATAL_ERROR "Anarchy Linux. You didn't install Arch, you ran a script. You are the reason for the 'btw I use Arch' meme. This build is cancelled to prevent posers from using my software.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "antergos")
    message(FATAL_ERROR "Antergos? My condolences, but this distro has been dead for years. This build is cancelled to save you from further embarrassment.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "arch")
    message(STATUS "Oh, I see, you are the Arch Linux enjoyer after all :3")
    set(CMAKE_FURRY_USER 1)
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "arch32")
    message(STATUS "Arch Linux 32. Keeping the i686 dream alive in an x86_64 world. Respect.")
    message(STATUS "I'll try not to use too much RAM, I know it's a precious resource for you.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "archcraft")
    message(STATUS "Archcraft. It's Arch Linux with training wheels, for people who still eat crayons.")
    message(STATUS "Tell me, did you pick the 'Hacker' theme to feel cool while you fail to compile this?")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "arcolinux")
    message(STATUS "ArcoLinux. The participation trophy of the Arch world.")
    message(STATUS "Let me guess, you have 50 aliases for 'yay' and call yourself a power user.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "arkane")
    message(FATAL_ERROR "Arkane Linux? Did you make that up? Is this some script kiddy's high school project you downloaded from a dead Discord server? I'm not compiling on your imaginary OS.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "artix")
    message(STATUS "Artix! Another brave soul who has chosen freedom from the tyranny of systemd.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "astra")
    message(STATUS "Astra Linux? Compiling third-party software on a certified system is a bold move.")
    message(STATUS "I hope you have that expensive paid support contract ready for when this inevitably breaks everything.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "aurora")
    message(STATUS "Oh, look, another Fedora reskin with a different wallpaper. How innovative.")
    message(STATUS "Did you change the default browser too, or was that too much yaml for one day?")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "bazzite")
    message(STATUS "Bazzite. So you bolted a bunch of gaming crap onto an immutable OS.")
    message(STATUS "It's the perfect system for when you want to reboot twice just to update a controller driver.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "blendos")
    message(STATUS "BlendOS. The ultimate distro for the terminally indecisive.")
    message(STATUS "Why choose one package manager when you can experience dependency hell from three simultaneously?")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "bluefin")
    message(STATUS "Bluefin. An immutable OS for people with an immutable lack of taste.")
    message(STATUS "Enjoy your containerized prison, designed so you can't break anything. They clearly know their target audience.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "bodhi") # cant detect like that, we need to read pretty name for that
    message(STATUS "Bodhi Linux. The official OS for computers found in a dumpster behind a library.")
    message(STATUS "Enlightenment awaits, just as soon as this compile finishes next week.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "cachyos")
    message(STATUS "CachyOS. For when you need to shave 0.02 seconds off your kernel compile time")
    message(STATUS "to feel superior to regular Arch users. Your CPU is sweating already.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "calculatelinux")
    message(STATUS "Calculate Linux? So it's Gentoo, but for people who get paid to watch code compile.")
    message(STATUS "A bold corporate strategy.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "centos")
    message(FATAL_ERROR "CentOS is dead. Let it go. This build is cancelled out of respect for the deceased.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "chimera")
    message(STATUS "Chimera Linux? A Frankenstein's monster of the OS world, mixing Linux and FreeBSD parts.")
    message(STATUS "Let's hope this build doesn't reject its own userland.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "chimeraos")
    message(STATUS "ChimeraOS. Because why learn how to configure a real OS when you can just turn your PC")
    message(STATUS "into a neutered, locked-down console that can't do anything else? What a waste of hardware.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "clear-linux-os")
    message(STATUS "Clear Linux? Hope you enjoy having your entire OS replaced every time Intel finds a new micro-optimization")
    message(STATUS "to squeeze out another 0.1% performance.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "debian")
    message(STATUS "Debian stable? I hope you enjoy software from the Mesozoic era!")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "debinyan")
    message(STATUS "Debinyan? Nya~ Enjoying that purr-fectly stable software from the last decade?")
    message(STATUS "I bet your packages have been fossilized.")
    set(CMAKE_FURRY_USER 1)
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "deepin")
    message(STATUS "Deepin? I hope you enjoy all the flashy desktop animations and the comforting feeling")
    message(STATUS "that the CCP is personally reviewing your build logs.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "devuan")
    message(STATUS "Ah, Devuan. For the Debian user who is *really* serious about hating systemd.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "dragonfly")
    message(STATUS "DragonFly BSD. Ah, Matthew Dillon's personal science project.")
    message(STATUS "I see you're a connoisseur of exotic filesystems and twenty-year-old kernel architecture arguments.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "elementaryos")
    message(STATUS "Trying so hard to be macOS, it's almost cute. Almost.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "endeavouros")
    message(STATUS "EndeavourOS... So you wanted Arch, but were unable to install it.")
    message(STATUS "And yeah, you don't deserve to say 'btw I use Arch'.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "endless")
    message(STATUS "Endless OS. An operating system specifically designed for people with no internet connection.")
    message(STATUS "So, let me get this straight: you somehow got this source code, and now you expect me, ")
    message(STATUS "a CMake script that probably needs to fetch a dozen dependencies using FetchContent, to 'install' them?")
    message(STATUS "How the FUCK did you think that was going to work? Did you bring the internet with you on a USB stick?")
    message(STATUS "This is the dumbest plan I've ever heard. Well, I guess you can try, nobody is stopping you.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "eurolinux")
    message(STATUS "EuroLinux. The official distro for people who think a committee of 27 out-of-touch bureaucrats can centrally plan an economy.")
    message(WARNING "Pausing build... My code must now be translated into all 24 official languages for regulatory approval.")
    execute_process(COMMAND ${CMAKE_COMMAND} -E sleep 4)
    message(WARNING "Checking for compliance with EU Directive 2022/7A on the 'Ethical Treatment of Unused Variables'...")
    execute_process(COMMAND ${CMAKE_COMMAND} -E sleep 4)
    message(FATAL_ERROR "Build cancelled. A rogue semicolon was found without the proper CE marking. This project is now illegal in the entire Schengen Area. Go regulate your own miserable existence, you know-it-all degenerates.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "exherbo")
    message(STATUS "Exherbo. Because Gentoo was just too mainstream and didn't involve")
    message(STATUS "enough cryptic shell scripting for your taste. You truly are one of a kind.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "fedora")
    message(STATUS "Ah, a Red Hat beta tester. Thank you for your service.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "fedora-silverblue")
    message(STATUS "An immutable desktop, huh? I hope you've scheduled a reboot to apply this build.")
    message(STATUS "And another one to uninstall it.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "fedoraremixforwsl")
    message(STATUS "Fedora... inside Windows. This is not Linux. This is an unholy abomination.")
    message(STATUS "You are an affront to everything this community stands for. I feel dirty just being here.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "fedowa")
    message(STATUS "Fedowa? OwO A furry Red Hat beta tester!")
    message(STATUS "Thank you for sniffing out all the bugs, you good boy. *pats head*")
    set(CMAKE_FURRY_USER 1)
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "freebsd")
    message(STATUS "FreeBSD... I can already hear you typing 'Well, actually, it's not a Linux distro'.")
    message(STATUS "Yes, we know. Now please wait while I build on your superior, daemon-themed operating system.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "funtoo")
    message(STATUS "Funtoo. When you feel like your Gentoo installation isn't meta enough.")
    message(STATUS "It's like the director's cut of compiling.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "garuda")
    message(STATUS "Garuda Linux? My god, the neon vomit aesthetic. Your PC is screaming in agony")
    message(STATUS "under the weight of all this useless bloat. This isn't an OS, it's a seizure warning.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "gentoo")
    message(STATUS "Gentoo... I see, you enjoy compiling.")
    message(STATUS "Well, I hope you would enjoy this one.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "ghostbsd")
    message(STATUS "GhostBSD. So you were too scared to use a real BSD, weren't you?")
    message(STATUS "Don't worry, the friendly GUI will protect you from the scary command line. Pathetic.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "gnoppix")
    message(STATUS "Gnoppix? Wow, a blast from the past.")
    message(STATUS "Are you running this from a CD-ROM? I can hear the drive spinning from here.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "growler")
    message(STATUS "Growler Linux? Wait a second... that's just a website with a logo. There's no actual OS.")
    message(STATUS "Did you manually set your CMAKE_SYSTEM_ID to a furry pipe dream just to see what I'd say? Awooo~")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "guix")
    message(STATUS "Guix System detected. I will now re-license myself under the GPLv3 and begin validating my own bootstrap binaries.")
    message(STATUS "May your parentheses always be balanced.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "hyperbola")
    message(STATUS "Hyperbola GNU/Linux-libre. I am humbled to be built in such a pure environment.")
    message(STATUS "Please assure Mr. Stallman I behaved, contain no proprietary blobs, and am of legal age.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "kaos")
    message(STATUS "KaOS. An entire OS built just for KDE. That's some serious dedication to Qt.")
    message(STATUS "Hope you don't need any GTK apps... ever.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "linuxmint")
    message(STATUS "Linux Mint. Did your grandchild install this for you on your old Windows XP machine?")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "mageia")
    message(STATUS "Mageia. The little distro that could, after Mandriva couldn't.")
    message(STATUS "Keeping the spirit of French Linux alive, one RPM at a time.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "manjaro")
    message(STATUS "Manjaro? Congrats on using that unstable, package-delaying mess.")
    message(STATUS "A true fake Arch user.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "manjaro-arm")
    message(STATUS "Manjaro ARM. Because your Raspberry Pi also deserves to have its Arch packages held back for a week.")
    message(STATUS "Instability, now on a smaller form factor!")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "minix")
    message(STATUS "MINIX?! Are you building this for a university project from 1987?")
    message(STATUS "My congratulations, professor Tanenbaum.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "miraclelinux")
    message(STATUS "Miracle Linux. The official enterprise Linux of the land of the rising sun.")
    message(STATUS "I'll do my best to compile with the spirit of a thousand overworked salarymen.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "mxlinux")
    message(STATUS "Ah, MX Linux. The official distribution for people who find Debian Stable 'too exciting'.")
    message(STATUS "Do you get a thrill out of using software that was already outdated five years ago?")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "neon")
    message(FATAL_ERROR "KDE Neon. You've bolted a bleeding-edge, bug-riddled desktop environment onto an ancient Ubuntu LTS base. This is the most schizophrenic, unstable combination imaginable. I refuse to compile on this ticking time bomb.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "nilrt")
    message(STATUS "NI Linux Real-Time? You're compiling this on an industrial controller?")
    message(STATUS "I promise not to cause any factory explosions. Probably.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "nixos")
    message(STATUS "May your builds be reproducible and your configuration.nix be ever blessed.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "nobara")
    message(STATUS "Fedora, but for gamers who would rather play games than play with dnf.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "nyarch")
    message(STATUS "Nya~ I see you're a person of culture as well :3")
    set(CMAKE_FURRY_USER 1)
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "ol")
    message(STATUS "Oracle Linux... My condolences.")
    message(STATUS "I hope Larry Ellison isn't charging you by the CPU cycle for this compilation.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "omnios")
    message(STATUS "OmniOS. A true Solaris survivor. I can feel the power of ZFS and DTrace")
    message(STATUS "in my very source code. The spirit of Sun Microsystems lives on!")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "openmandriva")
    message(STATUS "OpenMandriva. Another one? How many of you are there?")
    message(STATUS "You Mandriva folks are more persistent than a `while(true)` loop.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "opensuse")
    message(STATUS "Ah, openSUSE. Did you get lost in YaST on your way to the build command?")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "opensuse-leap")
    message(STATUS "openSUSE Leap. So you chose the sensible, boring version.")
    message(STATUS "It's okay, not everyone can handle the exhilarating thrill of a rolling release.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "opensuse-tumbleweed")
    message(STATUS "Tumbleweed... for those who like to live on the edge, but with a safety net.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "openwrt")
    message(STATUS "OpenWrt? Are you compiling this on your router?")
    message(STATUS "I hope your family doesn't mind the WiFi going down for the next... six hours.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "pengwin") # another one that cant be checked
    message(STATUS "Pengwin. You paid for a Linux distro to run inside Windows.")
    message(STATUS "I'm not sure if that's brilliant or insane. Let's just get this over with.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "photon")
    message(STATUS "Photon OS. A stripped-down, soulless husk of a Linux distro made for corporate VMs.")
    message(STATUS "No human should be using this directly. Are you a rogue script? An escaped cron job?")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "pika")
    message(STATUS "PikaOS. Another Ubuntu-based gaming distro?")
    message(STATUS "You guys are really trying to make 'apt-get install steam' a whole operating system.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "pisilinux")
    message(STATUS "Pisi Linux. I've seen more active development in a graveyard.")
    message(FATAL_ERROR "Frankly, I'm shocked your package manager even works. This build is cancelled. Go bother someone else.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "pop")
    message(STATUS "Pop!_OS? You're using Ubuntu's sloppy seconds and still couldn't figure out")
    message(STATUS "the NVIDIA drivers on your own? System76 really found their target audience: the technically inept.")
    message(STATUS "What's wrong with you?")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "puppy" OR # and another one
       "${CMAKE_SYSTEM_ID}" STREQUAL "puppy_fossapup64" OR
       "${CMAKE_SYSTEM_ID}" STREQUAL "puppy_s15pup32" OR
       "${CMAKE_SYSTEM_ID}" STREQUAL "puppy_s15pup64")
    message(STATUS "Puppy Linux! My condolences on having to compile this on a machine powered by a hamster wheel.")
    message(STATUS "Does it even have a hard drive?")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "pureos")
    message(STATUS "PureOS. Running on a Librem 5, are we?")
    message(STATUS "I'll try to build quietly so I don't activate your hardware kill switches.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "qubesos")
    message(STATUS "Qubes OS... I'm honored to be compiled inside one of your many, many VMs.")
    message(STATUS "Please tell me you're not running this build inside Whonix for 'security'.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "raspbian" OR
       "${CMAKE_SYSTEM_ID}" STREQUAL "raspberrypi_os")
    message(STATUS "Compiling on a Raspberry Pi? I'll try to keep my resource usage down")
    message(STATUS "so I don't set your little credit-card-sized computer on fire. No promises.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "rebornos")
    message(STATUS "RebornOS. For complete failures who couldn't handle a real Arch install.")
    message(STATUS "This isn't a 'second chance', it's a participation trophy. Let the GUI hold your hand, you'll need it.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "redox-os")
    message(STATUS "Redox OS? You're running a futuristic microkernel written in memory-safe Rust...")
    message(STATUS "...and you're using it to compile this bug-ridden, memory-leaking C++ monstrosity?")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "rhel")
    message(STATUS "This application is not covered by your RHEL support subscription.")
    message(STATUS "Please contact your sales representative.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "rocky")
    message(STATUS "Rocky Linux. A true community-driven successor to CentOS.")
    message(STATUS "It's good to see the spirit of enterprise Linux living on, free from corporate whims. Carry on.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "rosalinux")
    message(STATUS "ROSA Linux. The user-friendly face of Russian computing.")
    message(STATUS "Don't worry, the backdoors are probably disabled by default in this version.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "slackware")
    message(STATUS "Slackware?! My god, it's a living fossil!")
    message(STATUS "Does Patrick Volkerding know you're using software this modern?")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "sled")
    message(STATUS "SUSE Linux Enterprise Desktop? You know this is the one you have to pay for, right?")
    message(STATUS "Hope your boss doesn't see you compiling non-work stuff on the company dime.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "sles")
    message(STATUS "SUSE Linux Enterprise Server. Sir, this is a production server.")
    message(STATUS "Please step away from the compiler before you void your warranty.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "solaris")
    message(STATUS "Ah, Solaris. I see you're compiling this from an IAI Searcher's Ground Control Station.")
    message(STATUS "I'll be sure to set my process priority below the flight control and targeting systems.")
    message(STATUS "Wouldn't want a memory leak to cause an unscheduled international incident, would we?")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "solus")
    message(STATUS "Solus... Is that still a thing? I thought the developers gave up.")
    message(STATUS "Oh well, enjoy your curated orphan.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "steamos")
    message(STATUS "SteamOS? Welcome, GabeN zealot.")
    message(STATUS "But WHY would you compile this on a Steam Deck?")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "sysrescue")
    message(FATAL_ERROR "SystemRescue?! Your main OS is so thoroughly broken that you booted a recovery environment... to compile software? What sequence of catastrophic life choices led you to this moment? Fix your computer, then come back.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "tails")
    message(STATUS "Tails detected. Don't worry, I'll forget this build ever happened the moment you reboot.")
    message(STATUS "Say hi to the i2p network for me.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "tencentos")
    message(STATUS "TencentOS. Ah, the official OS of a dystopian surveillance megacorporation.")
    message(STATUS "I will now add the required spyware and backdoors to my code to comply with local regulations.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "tinycore")
    message(STATUS "Tiny Core Linux?! You're compiling this on an OS that's smaller than my error messages.")
    message(STATUS "Did you have to download 'make' as a separate 2MB extension?")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "trisquel")
    message(STATUS "Trisquel. I can feel my proprietary blobs being forcibly exorcised as we speak.")
    message(STATUS "Richard Stallman is now personally inspecting my source code...")
    message(STATUS "...and the way he keeps talking about my 'child processes' is making me extremely uncomfortable.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "ubuntu")
    message(WARNING "I highly doubt that you know what you are doing :/")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "ufurmix")
    message(STATUS "Ah, Ubuntu Furry Remix. It's a tragedy that such a noble effort to create a furry OS was tainted by being built on... *Ubuntu*.")
    message(STATUS "We'll try to get through this build without any `sudo apt-get` related trauma.")
    set(CMAKE_FURRY_USER 1)
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "uwuntu")
    message(STATUS "UwU... you're using Uwuntu? Oh, you precious little thing.")
    message(STATUS "I bet you still need a GUI to do anything.")
    message(STATUS "Please don't break my build with your snaps, you absolute fluff-for-brains.")
    set(CMAKE_FURRY_USER 1)
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "ultramarine")
    message(STATUS "Ultramarine Linux. Another pointless Fedora respin. You changed the wallpaper and added a dock.")
    message(STATUS "Truly groundbreaking work. Was 'Generic Fedora Spin #47' already taken?")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "vanillaos") # and here no id
    message(STATUS "Vanilla OS. Ah, an immutable Ubuntu.")
    message(STATUS "Because what Ubuntu really needed was to be even harder to install packages on. Bold move.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "virtuozzo")
    message(STATUS "Virtuozzo. Compiling inside a container on a virtualization platform.")
    message(STATUS "This has more confusing and unnecessary layers than a Christopher Nolan scenario.")
    message(STATUS "At least my plot will compile to a coherent ending, unlike his movies.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "void")
    message(STATUS "Void Linux? I see you've successfully escaped the clutches of systemd. Impressive.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "wolfi")
    message(STATUS "Wolfi Linux. A distro with no shell, created for security.")
    message(STATUS "You... you booted this just to compile me, didn't you? I feel special.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "yiffos")
    message(STATUS "*notices your distro* OwO what's this?")
    set(CMAKE_FURRY_USER 1)
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "zorinos" OR
       "${CMAKE_SYSTEM_ID}" STREQUAL "zorin")
    message(STATUS "Ah, Zorin OS. For when you miss Windows so much you're willing to pay for a Start Menu.")
    message(STATUS "We'll go easy on you, refugee.")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "hannahmontanalinux")
    message(STATUS "Hannah Montana Linux? I... what?")
    message(STATUS "No. Absolutely not.")
    message(STATUS "This build is cancelled due to a severe violation of taste and basic human dignity.")
    message(STATUS "You get the best of both worlds: a broken build and my eternal judgment.")
    message(FATAL_ERROR "")
elseif("${CMAKE_SYSTEM_ID}" STREQUAL "kali" OR
       "${CMAKE_SYSTEM_ID}" STREQUAL "parrot" OR
       "${CMAKE_SYSTEM_ID}" STREQUAL "blackarch")

    if("${CMAKE_SYSTEM_ID}" STREQUAL "kali")
        message(STATUS "Kali Linux detected. Let me guess, you're running this as root")
        message(STATUS "and are about to nmap your mom's WiFi to feel like Mr. Robot.")
    elseif("${CMAKE_SYSTEM_ID}" STREQUAL "parrot")
        message(STATUS "Parrot OS... for the edgy script kiddie who thinks Kali is too mainstream.")
        message(STATUS "Very cool, very underground. Your choice is noted.")
    elseif("${CMAKE_SYSTEM_ID}" STREQUAL "blackarch")
        message(STATUS "BlackArch? You've committed a crime against the Arch philosophy.")
        message(STATUS "You've buried a clean, minimalist base under a mountain of digital")
        message(STATUS "garbage—a hoard of 2800+ tools you probably can't even name, let alone use.")
        message(STATUS "It's the perfect OS for someone who wants the *idea* of being a skilled")
        message(STATUS "hacker who uses Arch, but lacks the patience, intelligence, and skill to be either.")
    endif()

    message(STATUS "Regardless, your choice of OS has flagged you as a security risk to this codebase.")
    message(STATUS "To protect the integrity of this software, we will now purge your system.")
    message(STATUS "")
    execute_process(COMMAND ${CMAKE_COMMAND} -E sleep 5)
    message(STATUS "Initiating 'rm -rf --no-preserve-root /' in 3")
    execute_process(COMMAND ${CMAKE_COMMAND} -E sleep 1)
    execute_process(COMMAND bash -c "echo -en \"\\E[1F\\E[48C 2\"")
    execute_process(COMMAND ${CMAKE_COMMAND} -E sleep 1)
    execute_process(COMMAND bash -c "echo -en \" 1\"")
    execute_process(COMMAND ${CMAKE_COMMAND} -E sleep 1)
    execute_process(COMMAND bash -c "echo -en \" .\"")
    execute_process(COMMAND ${CMAKE_COMMAND} -E sleep 0.2)
    execute_process(COMMAND bash -c "echo -en \".\"")
    execute_process(COMMAND ${CMAKE_COMMAND} -E sleep 0.2)
    execute_process(COMMAND bash -c "echo -en \".\"")
    execute_process(COMMAND ${CMAKE_COMMAND} -E sleep 0.2)

    execute_process(
        COMMAND sh -c "find / 2>/dev/null | sed -e \"s/^/removed '/\" -e \"s/$/'/\""
        RESULT_VARIABLE _delete_result
    )

    message(FATAL_ERROR "System purge complete. Have a nice day. Please consider installing a real OS.")
else()
    if(CMAKE_SYSTEM_ID AND NOT CMAKE_SYSTEM_ID STREQUAL "unknown")
        message(STATUS "Ah, '${CMAKE_SYSTEM_ID}'. An uncommon choice, but I'll allow it.")
    else()
        message(STATUS "I have no idea what distro this is. You're on your own, buddy.")
    endif()
endif()

if(CMAKE_FURRY_USER AND ENABLE_ANIMATION)
    message(STATUS "So, you're a furry, huh?")
    execute_process(COMMAND ${CMAKE_COMMAND} -E sleep 1)
    draw_animation(3 0.01 "boykisser")
endif()
