set(CURRENT_LIBRARY_NAME common)

set(CURRENT_SRC_DIR "${PROJECT_MAIN_SRC_DIR}/${CURRENT_LIBRARY_NAME}")
list_all_subdirectories("${CURRENT_SRC_DIR}" CURRENT_INCLUDE_DIRS)

file(GLOB_RECURSE CURRENT_SRC_FILES CONFIGURE_DEPENDS
    "${CURRENT_SRC_DIR}/*/*.hpp"
    "${CURRENT_SRC_DIR}/*/*.cpp"
)

source_group("Common" FILES ${CURRENT_SRC_FILES})

add_library(${CURRENT_LIBRARY_NAME} ${CURRENT_SRC_FILES})

add_library(xui::${CURRENT_LIBRARY_NAME} ALIAS ${CURRENT_LIBRARY_NAME})
set_target_properties(${CURRENT_LIBRARY_NAME} PROPERTIES OUTPUT_NAME "xui_${CURRENT_LIBRARY_NAME}")

list(APPEND PROJECT_INCLUDE_DIRS ${CURRENT_INCLUDE_DIRS})

target_include_directories(${CURRENT_LIBRARY_NAME}
    PUBLIC
        $<BUILD_INTERFACE:${PROJECT_INCLUDE_DIRS}>
        $<INSTALL_INTERFACE:include>
    PRIVATE
        ${CURRENT_INCLUDE_DIRS}
)

target_link_directories(${CURRENT_LIBRARY_NAME}    PRIVATE ${PROJECT_INCLUDE_DIRS})
target_link_libraries(${CURRENT_LIBRARY_NAME}      PRIVATE ${PROJECT_LIBRARIES_LIST})

# [SOME BUILD INFO]
string(TIMESTAMP COMPILE_TIME "%Y-%m-%d %H:%M:%S")

target_compile_definitions(${CURRENT_LIBRARY_NAME} PUBLIC
                           PROJECT_NAME="${PROJECT_NAME}"
                           PROJECT_DESCRIPTION="${PROJECT_DESCRIPTION}"
                           PROJECT_VERSION="${PROJECT_VERSION}"
                           PROJECT_APPLICATION_NAME="${PROJECT_APPLICATION_NAME}"
                           PROJECT_ORGANIZATION_NAME="${PROJECT_ORGANIZATION_NAME}"
                           PROJECT_ORGANIZATION_WEBSITE="${PROJECT_ORGANIZATION_WEBSITE}"
                           PROJECT_DEVELOPER_NAME="${PROJECT_DEVELOPER_NAME}"
                           PROJECT_DEVELOPER_EMAIL="${PROJECT_DEVELOPER_EMAIL}")

target_compile_definitions(${CURRENT_LIBRARY_NAME} PUBLIC
                            COMPILE_TIME="${COMPILE_TIME}"
                            COMPILER_ID="${CMAKE_CXX_COMPILER_ID}"
                            COMPILER_VERSION="${CMAKE_CXX_COMPILER_VERSION}")


target_compile_definitions(${CURRENT_LIBRARY_NAME} PUBLIC
                            SYSTEM_NAME="${CMAKE_SYSTEM_NAME}"
                            SYSTEM_VERSION="${CMAKE_SYSTEM_VERSION}"
                            SYSTEM_ID="${CMAKE_SYSTEM_ID}"
                            SYSTEM_PROCESSOR="${CMAKE_SYSTEM_PROCESSOR}"
                            SYSTEM_ARCHITECTURE="${CMAKE_SYSTEM_PROCESSOR}")

list(APPEND PROJECT_INCLUDE_DIRS ${CURRENT_SRC_DIR})
list(APPEND PROJECT_LIBRARIES_LIST ${CURRENT_LIBRARY_NAME})
list(APPEND PROJECT_TRANSLATION_TARGETS ${CURRENT_LIBRARY_NAME})
